# Generated by Django 5.2.8 on 2025-12-21 06:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing/')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=50, null=True)),
                ('dominant_color', models.CharField(max_length=30)),
                ('secondary_color', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_items', models.ManyToManyField(related_name='outfits', to='api.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('closet', 'Closet'), ('wardrobe', 'Wardrobe'), ('cupboard', 'Cupboard'), ('drawer', 'Drawer'), ('box', 'Box'), ('shelf', 'Shelf'), ('other', 'Other')], max_length=30)),
                ('is_put_away', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='api.storageunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_clothing_items', to=settings.AUTH_USER_MODEL)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misc_items', to='api.storageunit')),
            ],
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clothes', to='api.storageunit'),
        ),
    ]
