# Generated by Django 5.2.8 on 2026-02-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
