# Generated by Django 5.2.8 on 2026-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clothingitem_is_favourite_outfit_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
