# Generated by Django 5.2.8 on 2026-03-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_accessoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryitem',
            name='dominant_color',
        ),
        migrations.RemoveField(
            model_name='accessoryitem',
            name='secondary_color',
        ),
    ]
