# Generated by Django 5.2.8 on 2026-03-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_outfit_preview_and_accessory_fields'),
        ('api', '0007_remove_accessoryitem_dominant_color_and_more'),
    ]

    operations = [
    ]
