# Generated by Codex on 2026-03-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_admin_beta_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OutfitSuggestion",
        ),
    ]
