# Generated by Django 5.2.8 on 2026-04-04 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_clothingitem_fit_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betafeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
