# Generated by Django 5.2.8 on 2026-04-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_betafeedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='description',
        ),
    ]
