# Generated by Django 5.2.8 on 2026-04-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_storageunit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='clothing_items',
        ),
    ]
