from django.urls import path

from ..views.admin import (
    admin_activity,
    admin_clothing_detail,
    admin_clothing_list,
    admin_clothing_reclassify,
    admin_dashboard,
    admin_feedback_list,
    admin_feedback_mark_read,
    admin_invite_detail,
    admin_invites,
    admin_outfit_detail,
    admin_outfits_list,
    admin_send_password_reset,
    admin_set_user_active,
    admin_set_user_staff,
    admin_user_clothing,
    admin_user_outfits,
    admin_user_summary,
    admin_users,
)

urlpatterns = [
    path("dashboard/", admin_dashboard, name="admin_dashboard"),
    path("users/", admin_users, name="admin_users"),
    path("activity/", admin_activity, name="admin_activity"),
    path("users/<int:user_id>/active/", admin_set_user_active, name="admin_set_user_active"),
    path("users/<int:user_id>/staff/", admin_set_user_staff, name="admin_set_user_staff"),
    path("users/<int:user_id>/", admin_user_summary, name="admin_user_summary"),
    path("users/<int:user_id>/clothing/", admin_user_clothing, name="admin_user_clothing"),
    path("users/<int:user_id>/outfits/", admin_user_outfits, name="admin_user_outfits"),
    path("users/<int:user_id>/password-reset/", admin_send_password_reset, name="admin_send_password_reset"),
    path("invites/", admin_invites, name="admin_invites"),
    path("invites/<int:invite_id>/", admin_invite_detail, name="admin_invite_detail"),
    path("clothing/", admin_clothing_list, name="admin_clothing_list"),
    path("clothing/<int:item_id>/", admin_clothing_detail, name="admin_clothing_detail"),
    path("clothing/reclassify/", admin_clothing_reclassify, name="admin_clothing_reclassify"),
    path("outfits/", admin_outfits_list, name="admin_outfits_list"),
    path("outfits/<int:outfit_id>/", admin_outfit_detail, name="admin_outfit_detail"),
    path("feedback/", admin_feedback_list, name="admin_feedback_list"),
    path("feedback/<int:feedback_id>/read/", admin_feedback_mark_read, name="admin_feedback_mark_read"),
]
