### Register User
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "test",
  "email": "viom@test.com",
  "password": "12345678"
}

### Login User
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "username": "test",
  "password": "111111"
}